### ISSUE TITLE
CR::User Requirements::Dashboard:: Last_FY header not clear

### ISSUE THREAD

**Issue by howard-davis-ea** [EnvironmentAgency/pafs-user#10]
**Issue:**
Participants were unsure what the 'Last_FY' header on the dashboard table header stood for, and why it was relevant.
![dhastitle](https://cloud.githubusercontent.com/assets/17175769/14676133/01b93306-0704-11e6-845d-06f53d480c9c.PNG)

Participants were unclear why this information was being displayed on the dashboard. It was interpreted as not being relevant to them at this stage.

**Recommendation:**
To Be Discussed

**Comment by popshuvitdude** [comment]
This is taken out.
