### ISSUE TITLE
CR::User Requirements::Dashboard::Submitted column not clear

### ISSUE THREAD

**Issue by howard-davis-ea** [EnvironmentAgency/pafs-user#11]
**Issue:**
Participants were unsure what the 'Submitted' columns information was telling them? Was is when the proposal was last submitted? first submitted? Or something else?
![dhastitle](https://cloud.githubusercontent.com/assets/17175769/14676374/17e42518-0705-11e6-9a7c-20b8988e63c2.PNG)

**Recommendation:**
To Be Discussed.

**Comment by popshuvitdude** [comment]
Changed to Last submitted
