### ISSUE TITLE
CR::User Requirements::Dashboard::Columns require the ability to sort

### ISSUE THREAD

**Issue by howard-davis-ea** [EnvironmentAgency/pafs-user#12]
**Issue:**
Participants expected to be able to sort the dashboard columns to be able to easily find a specific project proposal.
![dhastitle](https://cloud.githubusercontent.com/assets/17175769/14676762/ccfcc36e-0706-11e6-85e7-8cf0759746d9.PNG)

**Recommendation:**
Apply sort functionality to each of the dashboard columns

**Comment by popshuvitdude** [comment]
Sort added to columns.
