### ISSUE TITLE
CR::User Requirements::Project Name:: Project Name field size too small

### ISSUE THREAD

**Issue by howard-davis-ea** [EnvironmentAgency/pafs-user#14]
**Issue:**
Participants were unable to view the whole project name within the text box. Stopping them from easily checking the project name entered
![project name](https://cloud.githubusercontent.com/assets/17175769/14677337/268e21fa-0709-11e6-884c-3b1df82bcf8e.PNG)

**Recommendation:**
Increase the size of text box

**Comment by popshuvitdude** [comment]
Text input box made bigger.
