### ISSUE TITLE
CR:: User Requirements:: Financial Year:: Financial Year Format

### ISSUE THREAD

**Issue by howard-davis-ea** [EnvironmentAgency/pafs-user#16]
Participants were unclear what year they were required to enter into the financial year box.
![financial year](https://cloud.githubusercontent.com/assets/17175769/14705504/d121a706-07b1-11e6-808a-8bbf75917076.PNG)

For example if the last financial year was 2017/18, participants were unclear if they should enter 2017 or 2018. Participants expected to have to enter 2017/18.

**Recommendation:**
To Be Discussed

**Comment by popshuvitdude** [comment]
Design changed.
