### ISSUE TITLE
CR:: User Requirements:: Funding Values:: Totals columns to be calculated automatically.

### ISSUE THREAD

**Issue by howard-davis-ea** [EnvironmentAgency/pafs-user#18]
**Issue:**
Participants expected the totals columns to be calculated automatically.
![funding value](https://cloud.githubusercontent.com/assets/17175769/14706461/a8904edc-07b6-11e6-9071-5fc3592f46bf.PNG)

Participants commented that by having the totals displayed and automatically calculated it enables them to easily see if they have made a mistake with the figures and acts a  sanity check.

**Recommendation:**
To Be Discussed

**Comment by popshuvitdude** [comment]
This would happen unless you have javascript turned off which should be zero % of our users.
