### ISSUE TITLE
CR:: USer Requirements:: Location:: Search Button

### ISSUE THREAD

**Issue by howard-davis-ea** [EnvironmentAgency/pafs-user#22]
**Issue:**
Participants overlooked the 'search' button, opting instead to 'save and continue'

![location](https://cloud.githubusercontent.com/assets/17175769/14709468/b7771d38-07c8-11e6-985d-c590ddb80be7.PNG)

Greater thought needs to be given in regard to the steps a participant will go through when using the mapping functionality. Participants expectations varied depending on the search term they used. For example if they searched by postcode, they expected the next step to be a list whereby they would confirm the correct postcode. However if they searched by a grid reference (more likely), they expected to be shown a map, on which they can then move to the specific area around which they wish to draw their polygon.

**Recommendation**
To Be Discussed

**Comment by popshuvitdude** [comment]
Final styling of page will be different.
