### ISSUE TITLE
CR:: USer Requirements:: Main Risk:: Remove Select All That Apply

### ISSUE THREAD

**Issue by howard-davis-ea** [EnvironmentAgency/pafs-user#24]
**Issue:**
Participants were confused by the option to 'select all that apply' despite the purpose of the page being to identify the main risk
![risks](https://cloud.githubusercontent.com/assets/17175769/14710554/b5be4002-07cd-11e6-8450-72f84408a9ae.PNG)

**Recommendation:**
Remove text ' select all that apply'

**Comment by popshuvitdude** [comment]
Changed.

**Comment by popshuvitdude** [comment]
Fixed.
