### ISSUE TITLE
CR:: User Requirements:: Standard Protection:: Question Currently Shows as percentage.

### ISSUE THREAD

**Issue by howard-davis-ea** [EnvironmentAgency/pafs-user#27]
**Issue:**
Participants questioned why coastal erosion standard of protection is currently show as a %. 
![statndard protection](https://cloud.githubusercontent.com/assets/17175769/14711627/0055368a-07d2-11e6-95b7-98d3631e7191.PNG)

Should this be displayed as Yrs. (as per the FCERM1 form)?

**Recommendation**
To Be Discussed

**Comment by popshuvitdude** [comment]
Changed.
