### ISSUE TITLE
CR:: User Requirements:: Calculator:: Separate Calculator

### ISSUE THREAD

**Issue by howard-davis-ea** [EnvironmentAgency/pafs-user#28]
**Issue:**
Participants expected the calculator to be within the web journey, rather than a separate entity. 
![funding calculator](https://cloud.githubusercontent.com/assets/17175769/14712882/d439afa4-07d6-11e6-8465-ae762abd8b74.PNG)

Participants noted that having the calculator outside of the core journey creates repetition, duplication of effort, requires downloading and uploading (which is not always possible) and version control issues. See additional slides for further explanation

**Recommendation**
To Be Discussed

**Comment by popshuvitdude** [comment]
Old news.
