### ISSUE TITLE
CR:: User Requirements:: Summary:: Save and Print

### ISSUE THREAD

**Issue by howard-davis-ea** [EnvironmentAgency/pafs-user#29]
**Issue:**
Participants expected to be able to save and print a copy of what they were going to submit.
![subsum](https://cloud.githubusercontent.com/assets/17175769/14712790/6c0da3f4-07d6-11e6-93d8-4d26113d4da0.PNG)

This was to enable them to send it to another person for review before they officially submitted. 

**Recommendation**
To B e Discussed

**Comment by popshuvitdude** [comment]
Duplicate ticket.
