### ISSUE TITLE
CR:: User Requirements:: All Pages:: Save and Continue

### ISSUE THREAD

**Issue by howard-davis-ea** [EnvironmentAgency/pafs-user#31]
**Issue:**
The functionality of the 'Don't save and continue' link was ambiguous.

Participants were unsure what the link on each page 'don't save and continue' allowed them to do - would it still keep the data already entered?
As a wider issue more discussion needs to take place around the rules of a page. E.g. How are part completed pages handled? Is a user able to exit without saving?

**Recommendation**
To Be Discussed

**Comment by popshuvitdude** [comment]
Changed to skip and continue. Ability to have partially completed pages is an ongoing one.
