### ISSUE TITLE
CR:: User Requirements:: Project Name:: Project Name Structure

### ISSUE THREAD

**Issue by howard-davis-ea** [EnvironmentAgency/pafs-user#38]
Participants were unclear around the structure and level of detail required when naming a project.
![project name](https://cloud.githubusercontent.com/assets/17175769/14741476/5812b0a2-088e-11e6-9be8-aea61add0968.PNG)

Participants requested an example of how to name a project.

**Recommendation**
To Be Discussed

**Comment by popshuvitdude** [comment]
Already done. We now have example names.
