### ISSUE TITLE
Phase 1 a::Dashboard:: No link to  proposal on dashboard

### ISSUE THREAD

**Issue by howard-davis-ea** [EnvironmentAgency/pafs-user#4]
1. Log in to PAFS and create a new project proposal. 
2. Create a new project application number and logout 
3. Log back in and navigate to the Dashboard.

Two things:

1. There is no link to open the project proposal from the dashboard.
2. The project appears to have a status of 'Approved'

<img width="1427" alt="dashboard" src="https://cloud.githubusercontent.com/assets/17175769/14561650/c660cc94-030f-11e6-9d95-d3016c96f937.PNG">

**Comment by tonyheadford** [comment]
Dashboard hasn't been done yet hence the cheeseipsum text. The RMA, location,Type and Status are all dummy values.

**Comment by howard-davis-ea** [comment]
Links to be existing proposals now present, Status field currently under review.

![links](https://cloud.githubusercontent.com/assets/17175769/14668793/dda44cce-06dd-11e6-8bcc-b93299f9c793.PNG)
