### ISSUE TITLE
CR:: User Requirements:: Reference Number:: Reference Number Should be displayed throughout the journey

### ISSUE THREAD

**Issue by howard-davis-ea** [EnvironmentAgency/pafs-user#40]
**Issue:**
Participants wanted to be able to see the project reference number throughout the entire journey so that they were confident at all times they were working / editing the correct proposal.
![refernceno](https://cloud.githubusercontent.com/assets/17175769/14742382/e0bb40c2-0893-11e6-8019-22688896a998.PNG)

**Recommendation**
Display project reference number within the page header

**Comment by popshuvitdude** [comment]
Done.
