### ISSUE TITLE
CR:: User Requirements::Funding Sources:: Not obvious that it is possible to enter many contributors in the text boxes

### ISSUE THREAD

**Issue by howard-davis-ea** [EnvironmentAgency/pafs-user#45]
**Issue:**
Participants were unaware that they are able to enter many contributors in the text boxes. In some instances they may require to enter many contributors.
![funding source](https://cloud.githubusercontent.com/assets/17175769/14743116/da7f440c-0897-11e6-8ce0-fbb32b783388.PNG)

In some circumstances there may be 100's of private contributors.

**Recommendation**
Consider putting contributor(s) instead of contributor

**Comment by popshuvitdude** [comment]
This is the wrong page.

**Comment by howard-davis-ea** [comment]
Which page should it be?

**Comment by popshuvitdude** [comment]
My bad. Its this page but your screenshot didn't show the expanded text fields.

**Comment by popshuvitdude** [comment]
Fixed. Provided large text fields.
