### ISSUE TITLE
CR:: User Requirements::Funding Sources:: ' further contributions' option 

### ISSUE THREAD

**Issue by howard-davis-ea** [EnvironmentAgency/pafs-user#48]
**Issue:**
Participants were unsure what the option ' further contributions' represented.
![funding source](https://cloud.githubusercontent.com/assets/17175769/14743390/4b6cb180-0899-11e6-9ae5-959d09dc0cdf.PNG)

**Recommendation**
To Be Discussed

**Comment by popshuvitdude** [comment]
Changed since issue raised.
