### ISSUE TITLE
CR:: User Requirements:: Funding Values: Not understanding the term Yr. -1

### ISSUE THREAD

**Issue by howard-davis-ea** [EnvironmentAgency/pafs-user#49]
**Issue:**
Participants did not understand the term Yr. -1. They would expect this to say 'previous years'.
![funding value](https://cloud.githubusercontent.com/assets/17175769/14743546/ea33475c-0899-11e6-9a0d-f5605b6e95d7.PNG)

**Recommendation**
Change the first column to read 'Previous Years'

**Comment by popshuvitdude** [comment]
Changed to previous years.
