### ISSUE TITLE
CR:: User Requirements:: Funding Values: Actual years should be displayed within the columns

### ISSUE THREAD

**Issue by howard-davis-ea** [EnvironmentAgency/pafs-user#50]
**Issue:**
Participants require to see actual years displayed within the columns (e.g. Y1 - 2014/15, Y2 -2015/16).
![funding value](https://cloud.githubusercontent.com/assets/17175769/14743595/29478caa-089a-11e6-96d0-8694aa07d07e.PNG)

Having the years explicitly displayed stops them from having to work it out in their heads. This is how it is displayed on the current FCERM1 form.

*Recommendation**
To Be Discussed

**Comment by popshuvitdude** [comment]
Changed
