### ISSUE TITLE
CR:: User Requirements:: Standard of Protection:: Standard of protection is currently show as a %

### ISSUE THREAD

**Issue by howard-davis-ea** [EnvironmentAgency/pafs-user#57]
**Issue:**
Coastal erosion standard of protection is currently show as a %. Should this be displayed as Yrs. (as per the FCERM1 form)?
![statndard protection](https://cloud.githubusercontent.com/assets/17175769/14779260/383ef5a4-0acf-11e6-881d-57af8ace07ea.PNG)

Check how coastal erosion standard of protection should be displayed.

**Recommendation**
To Be Discussed

**Comment by popshuvitdude** [comment]
Fixed
