### ISSUE TITLE
CR:: User Requirements:: DEFRA:: Order of this page

### ISSUE THREAD

**Issue by howard-davis-ea** [EnvironmentAgency/pafs-user#59]
**Issue:**
Participants questioned the order of this page. Should it go after the shoreline policy questions as hierarchically, Defra policy is a lower priority.

Check the priority order of these schemes. On the current FCERM 1 form DEFRA comes after the shoreline policy's

**Recommendation**
To Be Discussed

**Comment by popshuvitdude** [comment]
DEFRA section taken out.
