### ISSUE TITLE
CR:: User Requirements:: General:: Spelling Mistakes

### ISSUE THREAD

**Issue by howard-davis-ea** [EnvironmentAgency/pafs-user#69]
**Issue**
There existed a number of spelling mistakes within the PDF which participants picked up on including 'Levey', 'Check', stratagy', 'Please', Sorces'.

**Recommendation**
Make appropriate changes to spelling

**Comment by popshuvitdude** [comment]
No an issue now as we've moved on from the Balsamiq prototype.
