### ISSUE TITLE
CR::User Requirements::Dashboard: Approved Header not clear 

### ISSUE THREAD

**Issue by howard-davis-ea** [EnvironmentAgency/pafs-user#9]
**Issue:**
Participants were unsure what the 'Approved' header on the dashboard table represented, as there are many phases of approval, undertaken by a variety of people (e.g. PSO, Area, Local).

![dhastitle](https://cloud.githubusercontent.com/assets/17175769/14676020/99c8b96a-0703-11e6-93fe-1e0aa467ce20.PNG)

When a proposal is submitted there are many different phases of approval the proposal goes through before getting final overall funding. Participants were unclear what a status of approved represented.

**Recommendation:**
To Be Discussed

**Comment by popshuvitdude** [comment]
Decided to take this column out.
